name: Releaser-pleaser

on:
  push:
    branches: [main]

concurrency:
  group: releaser-pleaser
  cancel-in-progress: true

jobs:
  releaser-pleaser:
    if: github.repository == 'contentways/poweradmin-cli'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: releaser-pleaser
        uses: apricote/releaser-pleaser@v0.8.0
        with:
          token: ${{ secrets.RELEASER_PLEASER_TOKEN }}
